name: figure this out

run-name: "${{ github.actor }} is testing out GitHub Actions 🚀"

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

    steps:
      # Step 1: Check out code from repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Restore pacman cache
      - name: Restore Pacman Cache
        uses: actions/cache@v3
        with:
          path: /var/cache/pacman/pkg
          key: pacman-cache-${{ runner.os }}-${{ hashFiles('build.yml') }}
          restore-keys: |
            pacman-cache-${{ runner.os }}-

      # Step 3: Initialize pacman keyring and update system
      - name: Initialize and Update Arch Linux System
        run: |
          pacman-key --init                                  # Initialize pacman keyring for signature verification
          pacman-key --populate archlinux                    # Populate the Arch Linux keyring
          pacman -Syu --noconfirm                            # Update all packages to the latest versions


      # Step 4: Install BATS and Related Tools
      - name: Install BATS, bats-assert, bats-files, and bats-support
        run: pacman -S --noconfirm bats bats-assert bats-files bats-support

      # Step 5: Echo to show the workflow runs inside an Arch Linux container
      - name: Run commands in Arch Linux
        run: |
          echo "This is running inside an up-to-date Arch Linux container"
