name: figure this out

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  example-job:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel

   steps:
      # Step 1: Check out code from repository
      - name: Check out code
        uses: actions/checkout@v4

      # Step 2: Initialize pacman keyring and update system
      - name: Initialize and Update Arch Linux System
        run: |
          pacman-key --init                                  # Initialize pacman keyring for signature verification
          pacman-key --populate archlinux                    # Populate the Arch Linux keyring
          pacman -Syu --noconfirm                            # Update all packages to the latest versions

      # Step 3: Run some commands or install additional packages
#      - name: Install BATS
#        run: pacman -S --noconfirm bats

      # Step 4: Echo to show the workflow runs inside an Arch Linux container
      - name: Run commands in Arch Linux
        run: |
          echo "This is running inside an up-to-date Arch Linux container"
